### ISSUE TITLE
Please trigger CI

### ISSUE THREAD

**Issue by tdegeus** [conda-forge/pkgconfig-feedstock#21]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

The CI was not triggered after the last merge. Can anyone push an empty commit to trigger the CI?

**Comment by ocefpaf** [comment]
You now have the power to do it :smile: 

Want to try? If that does not work please ping me again and I'll do it.

**Comment by tdegeus** [comment]
Thanks!! Merging https://github.com/conda-forge/pkgconfig-feedstock/pull/22 did the trick this time.
